### ISSUE TITLE
PHAna needs update

### ISSUE THREAD

**Issue by haggerty** [sPHENIX-Collaboration/analysis#1]
analysis/Ana needs to be updated to account for several API changes (I think). 

The truth info has changed like this according to Mike McCumber:

This is a conflict with the new truth info design which forced the deprecation of that piece of the interface (poor encapsulation in the original object). To loop of the primary tracks you will need to use these lines:

    PHG4TruthInfoContainer::ConstRange range = truthinfo->GetPrimaryParticleRange();
    for (PHG4TruthInfoContainer::ConstIterator iter = range.first;
	iter != range.second; 
	++iter) {
      PHG4Particle* primary = iter->second;
    }

I think there must have been a change to the Fun4All input manager as well.

The example should probably have a small DST that can be used for testing and will always be available when the code is built.

**Comment by blackcathj** [comment]
Hi, John

Thank you reporting this problem. 

The code has been updated to fix the compiling issue via commit https://github.com/sPHENIX-Collaboration/analysis/commit/beb19a5353890568193332ba434ccf19355478cf . Please give a try. 

Currently, this repository was added to the Doxygen site (https://www.phenix.bnl.gov/WWW/sPHENIX/doxygen/html/), which hopefully help spotting such compatibility issues during future framework updates. 


> The example should probably have a small DST that can be used for testing and will always be available when the code is built. 

This is a good point. We considered options of nightly-build + tests. But never got to the stage of setting it up though. Right now it should work with the latest production outputs (most recent from GSU HCal workfest test production: /gpfs02/phenix/prod/sPHENIX/hcalfest/single_particle/spacal2d/)

**Comment by mccumbermike** [comment]
John also mentions an issue with the input manager. I think it might be a
const char* to std::string interface change. The macro may need a .c_str()
on one of the input names. I've had to do that when I was deep into testing
on a different branch and probably never bothered to cherry-pick the
individual commit back to the master macro.

Mike

--
Michael P. McCumber, PhD
Los Alamos National Laboratory
505-709-8161

**Comment by pinkenburg** [comment]
I need to  have a look. Vera asked me about this code at the hcal fest 
and it's just not suitable as example code for others to take over. I 
plan to replace it with something reasonable once I have a few minutes. 
The problem in the macro is the likely the use of "something different 
than what is in all example macros", namely using

char *infile = "...";
instead of
const char *infile ="..."

Chris

On 12/30/2015 2:20 PM, John Haggerty wrote:
>
> analysis/Ana needs to be updated to account for several API changes (I 
> think)
>
> The truth info has changed like this according to Mike McCumber:
>
> This is a conflict with the new truth info design which forced the 
> deprecation of that piece of the interface (poor encapsulation in the 
> original object) To loop of the primary tracks you will need to use 
> these lines:
>
> |PHG4TruthInfoContainer::ConstRange range = 
> truthinfo->GetPrimaryParticleRange(); for 
> (PHG4TruthInfoContainer::ConstIterator iter = rangefirst; iter != 
> rangesecond; ++iter) { PHG4Particle* primary = iter->second; } |
>
> I think there must have been a change to the Fun4All input manager as well
>
> The example should probably have a small DST that can be used for 
> testing and will always be available when the code is built
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sPHENIX-Collaboration/analysis/issues/1>.
>

-- 
*************************************************************

Christopher H. Pinkenburg	;    pinkenburg@bnl.gov
				;    http://www.phenix.bnl.gov/~pinkenbu

Brookhaven National Laboratory	;    phone: (631) 344-5692
Physics Department Bldg 510 C	;    fax:   (631) 344-3253
Upton, NY 11973-5000

*************************************************************

**Comment by haggerty** [comment]
Chris,

Happy New Year!  I was putzing around with it in my spare time over the 
holidays, and the immediate problem is fixed by:

> -  se->fileopen( hcal_dst->Name(), input_file );
> +  se->fileopen( hcal_dst->Name().c_str(), input_file );

and I didn't go much further, but I'm thinking in our new world, we 
should really make an attempt to keep anything in a public repository 
either working as-is or tagged as "broken" somehow.  Fixing one error in 
a package is a pain, but possible.  Fixing two can be time consuming. 
Fixing three can be baffling, and trying to fix four generally leads to 
starting over from scratch or taking ugly shortcuts.

I know you're not fond of root, but one thing they do really well is 
keep their example code working.  I find it is often not the best code 
that could be written, but it shows how to use the objects.

I saw your picture and story in the Three Village times--congratulations!

On 12/30/15 4:13 PM, pinkenburg wrote:
> I need to have a look. Vera asked me about this code at the hcal fest
> and it's just not suitable as example code for others to take over. I
> plan to replace it with something reasonable once I have a few minutes.
> The problem in the macro is the likely the use of "something different
> than what is in all example macros", namely using
>
> char *infile = "...";
> instead of
> const char *infile ="..."
>
> Chris
>
> On 12/30/2015 2:20 PM, John Haggerty wrote:
>  >
>  > analysis/Ana needs to be updated to account for several API changes (I
>  > think)
>  >
>  > The truth info has changed like this according to Mike McCumber:
>  >
>  > This is a conflict with the new truth info design which forced the
>  > deprecation of that piece of the interface (poor encapsulation in the
>  > original object) To loop of the primary tracks you will need to use
>  > these lines:
>  >
>  > |PHG4TruthInfoContainer::ConstRange range =
>  > truthinfo->GetPrimaryParticleRange(); for
>  > (PHG4TruthInfoContainer::ConstIterator iter = rangefirst; iter !=
>  > rangesecond; ++iter) { PHG4Particle* primary = iter->second; } |
>  >
>  > I think there must have been a change to the Fun4All input manager as
> well
>  >
>  > The example should probably have a small DST that can be used for
>  > testing and will always be available when the code is built
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  > <https://github.com/sPHENIX-Collaboration/analysis/issues/1>.
>  >
>
> --
> *************************************************************
>
> Christopher H. Pinkenburg ; pinkenburg@bnl.gov
> ; http://www.phenix.bnl.gov/~pinkenbu
>
> Brookhaven National Laboratory ; phone: (631) 344-5692
> Physics Department Bldg 510 C ; fax: (631) 344-3253
> Upton, NY 11973-5000
>
> *************************************************************
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sPHENIX-Collaboration/analysis/issues/1#issuecomment-168074583>.
>


-- 
John Haggerty
email: haggerty@bnl.gov
cell: 631 741 3358

**Comment by mccumbermike** [comment]
John,

I tried to patch this 5 days ago after direct mention of the issue in my
reply to you---I hope you didn't spend too many cycles on it. See:
https://github.com/sPHENIX-Collaboration/macros/commit/73c9827a2713685de56d9e114105e18e7098c650

Did I miss the location of this c_str() in my patch? I don't recognize this
line from the actual example macros.

Mike

--
Michael P. McCumber, PhD
Los Alamos National Laboratory
505-709-8161

**Comment by haggerty** [comment]
Mike,

Thanks, no, I spent only a couple minutes between various cooking 
chores, but I didn't notice the fix and thought I'd mention it to close 
the email loop.

On 1/4/16 11:33 PM, Michael P. McCumber wrote:
> John,
>
> I tried to patch this 5 days ago after direct mention of the issue in my
> reply to you---I hope you didn't spend too many cycles on it. See:
> https://github.com/sPHENIX-Collaboration/macros/commit/73c9827a2713685de56d9e114105e18e7098c650
>
> Did I miss the location of this c_str() in my patch? I don't recognize this
> line from the actual example macros.
>
> Mike
>
> --
> Michael P. McCumber, PhD
> Los Alamos National Laboratory
> 505-709-8161
>
> On Mon, Jan 4, 2016 at 9:21 PM, John Haggerty <notifications@github.com>
> wrote:
>
>  > Chris,
>  >
>  > Happy New Year! I was putzing around with it in my spare time over the
>  > holidays, and the immediate problem is fixed by:
>  >
>  > > - se->fileopen( hcal_dst->Name(), input_file );
>  > > + se->fileopen( hcal_dst->Name().c_str(), input_file );
>  >
>  > and I didn't go much further, but I'm thinking in our new world, we
>  > should really make an attempt to keep anything in a public repository
>  > either working as-is or tagged as "broken" somehow. Fixing one error in
>  > a package is a pain, but possible. Fixing two can be time consuming.
>  > Fixing three can be baffling, and trying to fix four generally leads to
>  > starting over from scratch or taking ugly shortcuts.
>  >
>  > I know you're not fond of root, but one thing they do really well is
>  > keep their example code working. I find it is often not the best code
>  > that could be written, but it shows how to use the objects.
>  >
>  > I saw your picture and story in the Three Village times--congratulations!
>  >
>  > On 12/30/15 4:13 PM, pinkenburg wrote:
>  > > I need to have a look. Vera asked me about this code at the hcal fest
>  > > and it's just not suitable as example code for others to take over. I
>  > > plan to replace it with something reasonable once I have a few minutes.
>  > > The problem in the macro is the likely the use of "something different
>  > > than what is in all example macros", namely using
>  > >
>  > > char *infile = "...";
>  > > instead of
>  > > const char *infile ="..."
>  > >
>  > > Chris
>  > >
>  > > On 12/30/2015 2:20 PM, John Haggerty wrote:
>  > > >
>  > > > analysis/Ana needs to be updated to account for several API
> changes (I
>  > > > think)
>  > > >
>  > > > The truth info has changed like this according to Mike McCumber:
>  > > >
>  > > > This is a conflict with the new truth info design which forced the
>  > > > deprecation of that piece of the interface (poor encapsulation in the
>  > > > original object) To loop of the primary tracks you will need to use
>  > > > these lines:
>  > > >
>  > > > |PHG4TruthInfoContainer::ConstRange range =
>  > > > truthinfo->GetPrimaryParticleRange(); for
>  > > > (PHG4TruthInfoContainer::ConstIterator iter = rangefirst; iter !=
>  > > > rangesecond; ++iter) { PHG4Particle* primary = iter->second; } |
>  > > >
>  > > > I think there must have been a change to the Fun4All input manager as
>  > > well
>  > > >
>  > > > The example should probably have a small DST that can be used for
>  > > > testing and will always be available when the code is built
>  > > >
>  > > > —
>  > > > Reply to this email directly or view it on GitHub
>  > > > <https://github.com/sPHENIX-Collaboration/analysis/issues/1>.
>  > > >
>  > >
>  > > --
>  > > *************************************************************
>  > >
>  > > Christopher H. Pinkenburg ; pinkenburg@bnl.gov
>  > > ; http://www.phenix.bnl.gov/~pinkenbu
>  > >
>  > > Brookhaven National Laboratory ; phone: (631) 344-5692
>  > > Physics Department Bldg 510 C ; fax: (631) 344-3253
>  > > Upton, NY 11973-5000
>  > >
>  > > *************************************************************
>  > >
>  > > —
>  > > Reply to this email directly or view it on GitHub
>  > > <
>  >
> https://github.com/sPHENIX-Collaboration/analysis/issues/1#issuecomment-168074583
>  > >.
>  > >
>  >
>  >
>  > --
>  > John Haggerty
>  > email: haggerty@bnl.gov
>  > cell: 631 741 3358
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/sPHENIX-Collaboration/analysis/issues/1#issuecomment-168892042>
>  > .
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sPHENIX-Collaboration/analysis/issues/1#issuecomment-168893800>.
>


-- 
John Haggerty
email: haggerty@bnl.gov
cell: 631 741 3358
